### ISSUE TITLE
What is the syntax for multiple target URLs?

### ISSUE THREAD

**Issue by pascalandy** [kenju/github-actions-artillery#1]
Here is what I have in mind.
Thanks!

```
config:
  target: | 
      https://example.net/
      https://example.net/products/
      https://example.net/about/
  phases:
    - duration: 30 #sec
      arrivalRate: 2

scenarios:
  - name: load test
    flow:
      - get:
          url: /
```
